name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build app
      run: |
        xcodebuild -project WakeyWakey.xcodeproj -scheme WakeyWakey -configuration Release -archivePath ./WakeyWakey.xcarchive archive
        
    - name: Create ExportOptions.plist
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>developer-id</string>
            <key>teamID</key>
            <string>YOUR_TEAM_ID</string>
            <key>signingStyle</key>
            <string>automatic</string>
        </dict>
        </plist>
        EOF
        
    - name: Export app
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        xcodebuild -exportArchive -archivePath ./WakeyWakey.xcarchive -exportPath ./export -exportOptionsPlist ExportOptions.plist
        
    - name: Create DMG
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        brew install create-dmg
        create-dmg \
          --volname "Wakey Wakey" \
          --volicon "WakeyWakey/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png" \
          --background "DMG-background.png" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "WakeyWakey.app" 200 190 \
          --hide-extension "WakeyWakey.app" \
          --app-drop-link 600 185 \
          "WakeyWakey.dmg" \
          "./export/WakeyWakey.app"
          
    - name: Upload app artifact
      uses: actions/upload-artifact@v3
      with:
        name: WakeyWakey.app
        path: ./export/WakeyWakey.app
        
    - name: Upload DMG artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v3
      with:
        name: WakeyWakey.dmg
        path: ./WakeyWakey.dmg
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Wakey Wakey ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          ./WakeyWakey.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
