name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build app
      run: |
        # Build directly using Swift Package Manager
        swift build -c release
        
        # Create a directory for the app bundle
        mkdir -p ./build/WakeyWakey.app/Contents/MacOS
        
        # Copy the executable to the app bundle
        cp .build/release/WakeyWakey ./build/WakeyWakey.app/Contents/MacOS/
        
        # Create a basic Info.plist
        cat > ./build/WakeyWakey.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>WakeyWakey</string>
            <key>CFBundleIdentifier</key>
            <string>com.joelio.wakeywakey</string>
            <key>CFBundleName</key>
            <string>WakeyWakey</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
            <key>LSUIElement</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        # Create a directory for resources
        mkdir -p ./build/WakeyWakey.app/Contents/Resources
        
        # Copy assets
        cp -R WakeyWakey/Assets.xcassets ./build/WakeyWakey.app/Contents/Resources/
        
        # Create an archive
        mkdir -p WakeyWakey.xcarchive/Products/Applications
        cp -R ./build/WakeyWakey.app WakeyWakey.xcarchive/Products/Applications/
        
    - name: Create ExportOptions.plist
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>developer-id</string>
            <key>teamID</key>
            <string>YOUR_TEAM_ID</string>
            <key>signingStyle</key>
            <string>automatic</string>
        </dict>
        </plist>
        EOF
        
    - name: Export app
      run: |
        # Copy the app bundle to the export directory
        mkdir -p ./export
        cp -R ./build/WakeyWakey.app ./export/
        
    - name: Create DMG
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        brew install create-dmg
        create-dmg \
          --volname "Wakey Wakey" \
          --volicon "WakeyWakey/Assets.xcassets/AppIcon.appiconset/wakey-wakey-icon.png" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "WakeyWakey.app" 200 190 \
          --hide-extension "WakeyWakey.app" \
          --app-drop-link 600 185 \
          "WakeyWakey.dmg" \
          "./export/WakeyWakey.app"
          
    - name: Package app for artifact
      run: |
        cd ./export
        zip -r WakeyWakey.zip WakeyWakey.app
        
    - name: Upload app artifact
      uses: actions/upload-artifact@v4
      with:
        name: WakeyWakey
        path: ./export/WakeyWakey.zip
        
    - name: Upload DMG artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: WakeyWakey.dmg
        path: ./WakeyWakey.dmg
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Wakey Wakey ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          ./WakeyWakey.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
