name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build app
      run: |
        # Build directly using Swift Package Manager
        swift build -c release
        
        # Create directories for the app bundle
        mkdir -p ./build/WakeyWakey.app/Contents/{MacOS,Resources}
        
        # Copy the executable to the app bundle and ensure it's executable
        cp .build/release/WakeyWakey ./build/WakeyWakey.app/Contents/MacOS/
        chmod +x ./build/WakeyWakey.app/Contents/MacOS/WakeyWakey
        
        # Create PkgInfo file (required for proper app bundle)
        echo 'APPL????' > ./build/WakeyWakey.app/Contents/PkgInfo
        
        # Extract version from tag or use default
        if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Building version $VERSION from tag"
        else
          VERSION="1.0.0"
          echo "No tag found, using default version $VERSION"
        fi
        
        # Create a complete Info.plist with all necessary keys
        cat > ./build/WakeyWakey.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>en</string>
            <key>CFBundleExecutable</key>
            <string>WakeyWakey</string>
            <key>CFBundleIconFile</key>
            <string>AppIcon</string>
            <key>CFBundleIconName</key>
            <string>AppIcon</string>
            <key>CFBundleIdentifier</key>
            <string>com.joelio.wakeywakey</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>WakeyWakey</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>$VERSION</string>
            <key>CFBundleVersion</key>
            <string>$VERSION</string>
            <key>LSApplicationCategoryType</key>
            <string>public.app-category.utilities</string>
            <key>LSMinimumSystemVersion</key>
            <string>11.0</string>
            <key>LSUIElement</key>
            <true/>
            <key>NSHumanReadableCopyright</key>
            <string>Copyright © 2025 joelio. All rights reserved.</string>
            <key>NSPrincipalClass</key>
            <string>NSApplication</string>
            <key>NSSupportsAutomaticTermination</key>
            <true/>
            <key>NSSupportsSuddenTermination</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        # Compile assets using actool instead of copying raw assets
        xcrun actool --compile ./build/WakeyWakey.app/Contents/Resources \
          --minimum-deployment-target 11.0 \
          --platform macosx \
          --app-icon AppIcon \
          --output-partial-info-plist ./build/assetcatalog_generated_info.plist \
          WakeyWakey/Assets.xcassets
        
        # Create an archive
        mkdir -p WakeyWakey.xcarchive/Products/Applications
        cp -R ./build/WakeyWakey.app WakeyWakey.xcarchive/Products/Applications/
        
    - name: Create ExportOptions.plist
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>developer-id</string>
            <key>teamID</key>
            <string>YOUR_TEAM_ID</string>
            <key>signingStyle</key>
            <string>automatic</string>
        </dict>
        </plist>
        EOF
        
    - name: Export app
      run: |
        # Copy the app bundle to the export directory
        mkdir -p ./export
        cp -R ./build/WakeyWakey.app ./export/
        
    - name: Create DMG
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        brew install create-dmg
        create-dmg \
          --volname "Wakey Wakey" \
          --volicon "WakeyWakey/Assets.xcassets/AppIcon.appiconset/wakey-wakey-icon.png" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "WakeyWakey.app" 200 190 \
          --hide-extension "WakeyWakey.app" \
          --app-drop-link 600 185 \
          "WakeyWakey.dmg" \
          "./export/WakeyWakey.app"
          
    - name: Package app for artifact
      run: |
        # Create a disk image to preserve the .app bundle structure
        hdiutil create -volname "WakeyWakey" -srcfolder ./export/WakeyWakey.app -ov -format UDZO ./export/WakeyWakey.dmg
        
    - name: Upload app artifact
      uses: actions/upload-artifact@v4
      with:
        name: WakeyWakey
        path: ./export/WakeyWakey.dmg
        
    - name: Upload DMG artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: WakeyWakey.dmg
        path: ./WakeyWakey.dmg
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Wakey Wakey ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          ./WakeyWakey.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Output Release Info for Homebrew
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "=== Release Information for Homebrew Formula =="
        echo "Version: ${GITHUB_REF#refs/tags/v}"
        echo "Download URL: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/WakeyWakey.dmg"
        echo "To update your Homebrew formula, use this information in your formula's URL and version fields."
